# Name of your application. Used to uniquely configure containers.
service: ruby_lab

# Name of the container image.
image: caisilus/ruby_lab

# Deploy to these servers.
servers:
  - 77.91.123.194

# Credentials for your image host.
registry:
  username: caisilus

  # Always use an access token rather than real password when possible.
  password:
    - MRSK_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
env:
 clear:
   DB_HOST: 77.91.123.194
   REDIS_URL: "redis://77.91.123.194:6379/1"
   RAILS_SERVE_STATIC_FILES: true
   RAILS_LOG_TO_STDOUT: true
   SANDBOX_DIRECTORY: "/rails/sandbox"
 secret:
   - RAILS_MASTER_KEY
   - GITHUB_CLIENT_ID
   - GITHUB_CLIENT_SECRET
   - POSTGRES_PASSWORD

# Volumes for app container
volumes:
  - "~/ruby_lab_app/sandbox:/rails/sandbox"

# Use accessory services (secrets come from .env).
accessories:
 db:
   image: postgres:latest
   host: 77.91.123.194
   port: 5432
   env:
     clear:
       POSTGRES_USER: ruby_lab
     secret:
       - POSTGRES_PASSWORD
   directories:
     - data:/var/lib/postgresql/data
 redis:
   image: redis:7.0
   host: 77.91.123.194
   port: 6379
   directories:
     - data:/data
